name: continuous-integration

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - --all-features
          - --no-default-features
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Check
      run: cargo check ${{ matrix.features }}
    - name: Build
      run: cargo build ${{ matrix.features }}
    - name: Test
      run: cargo test ${{ matrix.features }}
